controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - axis_joint_1
      - axis_joint_2
      - axis_joint_3
      - axis_joint_4
      - axis_joint_5
      - axis_joint_6
initial:  # Define initial robot poses.
#  - group: manipulator
#    pose: home

  []