trajectory:
  type: position_controllers/JointTrajectoryController
  joints:
     - axis_joint_1
     - axis_joint_2
     - axis_joint_3
     - axis_joint_4
     - axis_joint_5
     - axis_joint_6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      axis_joint_1: {trajectory: 0.1, goal: 0.1}
      axis_joint_2: {trajectory: 0.1, goal: 0.1}
      axis_joint_3: {trajectory: 0.1, goal: 0.1}
      axis_joint_4: {trajectory: 0.1, goal: 0.1}
      axis_joint_5: {trajectory: 0.1, goal: 0.1}
      axis_joint_6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - axis_joint_1
     - axis_joint_2
     - axis_joint_3
     - axis_joint_4
     - axis_joint_5
     - axis_joint_6

